apiVersion: v1
kind: ConfigMap
metadata:
  name: planner-config
  namespace: {{ .Values.namespace }}
  labels:
    app: inference-design-planner
data:
  APP_ENV: {{ .Values.config.APP_ENV | quote }}
  APP_LOG_LEVEL: {{ .Values.config.APP_LOG_LEVEL | quote }}
  APP_CORS_ORIGINS: {{ .Values.config.APP_CORS_ORIGINS | quote }}
  LLM_MODEL_NAME: {{ .Values.config.LLM_MODEL_NAME | quote }}
  VERIFY_SSL: {{ .Values.config.VERIFY_SSL | quote }}
  MLFLOW_TRACKING_URI: {{ .Values.config.MLFLOW_TRACKING_URI | quote }}
  MLFLOW_TRACKING_INSECURE_TLS: {{ .Values.config.MLFLOW_TRACKING_INSECURE_TLS | quote }}
  MLFLOW_WORKSPACE: {{ .Values.config.MLFLOW_WORKSPACE | quote }}
  MLFLOW_EXPERIMENT_NAME: {{ .Values.config.MLFLOW_EXPERIMENT_NAME | quote }}
  PROMETHEUS_ENABLED: {{ .Values.config.PROMETHEUS_ENABLED | quote }}
  SEARXNG_URL: {{ .Values.config.SEARXNG_URL | quote }}
  HF_HOME: "/tmp/hf_cache"
