apiVersion: v1
kind: Secret
metadata:
  name: planner-secrets
  namespace: {{ .Values.namespace }}
  labels:
    app: inference-design-planner
type: Opaque
stringData:
  OPENAI_API_KEY: {{ .Values.secret.OPENAI_API_KEY | quote }}
  OPENAI_BASE_URL: {{ .Values.secret.OPENAI_BASE_URL | quote }}
  DATABASE_URL: {{ .Values.secret.DATABASE_URL | quote }}
  DATABASE_URL_SYNC: {{ .Values.secret.DATABASE_URL_SYNC | quote }}
  MLFLOW_TRACKING_TOKEN: {{ .Values.secret.MLFLOW_TRACKING_TOKEN | quote }}
  {{- if .Values.secret.HF_TOKEN }}
  HF_TOKEN: {{ .Values.secret.HF_TOKEN | quote }}
  {{- end }}
